In [1]:
import numpy as np
import pandas as pd

In [3]:
rt = np.arange(45)
rt

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [19]:
arr1 = np.array([[10,12,13,14],
               [20,21,23,24]])
arr2 = np.array([[100,120,130,140]])

array([[100, 120, 130, 140]])

In [20]:
arr1+arr2

array([[110, 132, 143, 154],
       [120, 141, 153, 164]])

In [21]:
print(np.concatenate((arr1,arr2)))

[[ 10  12  13  14]
 [ 20  21  23  24]
 [100 120 130 140]]


In [2]:
#DataFrame

In [6]:
country =['India','Russia','Australia','UK','Canada','SouthAfrica','New Zealand','Japan']

In [7]:
country_df = pd.DataFrame(country,columns=['Country_Name'],index = list(range(1,9)))

In [9]:
area = [3.28,16.38,7.68,9.16,9.09,1.21,2.67,3.64]
area_df = pd.DataFrame(area,columns=['Area(msqkm.)'],index = list(range(1,9)))

In [11]:
country_area_df = list(zip(country,area))
country_area_df

[('India', 3.28),
 ('Newzealand', 16.38),
 ('Australia', 7.68),
 ('UK', 9.16),
 ('Canada', 9.09),
 ('SouthAfrica', 1.21),
 ('Srilanka', 2.67),
 ('Japan', 3.64)]

In [13]:
coun_area_df = pd.DataFrame(country_area_df,columns=['Country_Name','Area(Msqkm.)'],index =list(range(1,9)))
coun_area_df

Country_Name  Area(Msqkm.)
1        India          3.28
2   Newzealand         16.38
3    Australia          7.68
4           UK          9.16
5       Canada          9.09
6  SouthAfrica          1.21
7     Srilanka          2.67
8        Japan          3.64

In [8]:
#To read the file 
re = pd.read_csv('D:/cricket dataset/points_table.csv')
re

season  rank                         name short_name  matchesplayed  \
0    2022     1               Gujarat Titans         GT             14   
1    2022     2             Rajasthan Royals         RR             14   
2    2022     3         Lucknow Super Giants        LSG             14   
3    2022     4  Royal Challengers Bangalore        RCB             14   
4    2022     5               Delhi Capitals         DC             14   
5    2022     6                 Punjab Kings       KXIP             14   
6    2022     7        Kolkata Knight Riders        KKR             14   
7    2022     8          Sunrisers Hyderabad        SRH             14   
8    2022     9          Chennai Super Kings        CSK             14   
9    2022    10               Mumbai Indians         MI             14   

   matcheswon  matcheslost  noresult  matchpoints    nrr         for  \
0          10            4         0           20  0.316  2339/278.1   
1           9            5         0           18  0.298  2464/279.2   
2           9            5         0           18  0.251  2355/279.1   
3           8            6         0           16 -0.253  2268/275.4   
4           7            7         0           14  0.204  2341/266.0   
5           7            7         0           14  0.126  2343/270.1   
6           6            8         0           12  0.146  2223/268.1   
7           6            8         0           12 -0.379  2197/261.3   
8           4           10         0            8 -0.203  2288/280.0   
9           4           10         0            8 -0.506  2217/273.2   

      against  
0  2216/273.5  
1  2351/275.5  
2  2289/279.4  
3  2260/266.3  
4  2397/278.5  
5  2252/263.3  
6  2249/276.1  
7  2416/275.1  
8  2254/269.1  
9  2351/272.5

In [4]:
re.head()

season  rank                         name short_name  matchesplayed  \
0    2022     1               Gujarat Titans         GT             14   
1    2022     2             Rajasthan Royals         RR             14   
2    2022     3         Lucknow Super Giants        LSG             14   
3    2022     4  Royal Challengers Bangalore        RCB             14   
4    2022     5               Delhi Capitals         DC             14   

   matcheswon  matcheslost  noresult  matchpoints    nrr         for  \
0          10            4         0           20  0.316  2339/278.1   
1           9            5         0           18  0.298  2464/279.2   
2           9            5         0           18  0.251  2355/279.1   
3           8            6         0           16 -0.253  2268/275.4   
4           7            7         0           14  0.204  2341/266.0   

      against  
0  2216/273.5  
1  2351/275.5  
2  2289/279.4  
3  2260/266.3  
4  2397/278.5

In [5]:
re.tail()

season  rank                         name short_name  matchesplayed  \
121    2008     4               Delhi Capitals         DC             14   
122    2008     5               Mumbai Indians         MI             14   
123    2008     6        Kolkata Knight Riders        KKR             14   
124    2008     7  Royal Challengers Bangalore        RCB             14   
125    2008     8              Deccan Chargers        SRH             14   

     matcheswon  matcheslost  noresult  matchpoints    nrr         for  \
121           7            6         1           15  0.342  2001/233.2   
122           7            7         0           14  0.570  2080/249.1   
123           6            7         1           13 -0.147  1845/242.4   
124           4           10         0            8 -1.160  1983/272.4   
125           2           12         0            4 -0.467  2229/270.0   

        against  
121  2031/246.4  
122  2096/269.3  
123  1718/221.4  
124  2205/261.3  
125  2307/264.3

In [9]:
re.describe()

season      rank  matchesplayed  matcheswon  matcheslost  noresult  \
count    10.0  10.00000           10.0   10.000000    10.000000      10.0   
mean   2022.0   5.50000           14.0    7.000000     7.000000       0.0   
std       0.0   3.02765            0.0    2.054805     2.054805       0.0   
min    2022.0   1.00000           14.0    4.000000     4.000000       0.0   
25%    2022.0   3.25000           14.0    6.000000     5.250000       0.0   
50%    2022.0   5.50000           14.0    7.000000     7.000000       0.0   
75%    2022.0   7.75000           14.0    8.750000     8.000000       0.0   
max    2022.0  10.00000           14.0   10.000000    10.000000       0.0   

       matchpoints           nrr  
count    10.000000  1.000000e+01  
mean     14.000000 -2.220446e-17  
std       4.109609  3.046608e-01  
min       8.000000 -5.060000e-01  
25%      12.000000 -2.405000e-01  
50%      14.000000  1.360000e-01  
75%      17.500000  2.392500e-01  
max      20.000000  3.160000e-01

In [7]:
re = pd.read_csv('D:/cricket dataset/points_table.csv','sheet 1')
re

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3369: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\admin\AppData\Local\Temp\ipykernel_10732\280635296.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  re = pd.read_csv('D:/cricket dataset/points_table.csv','sheet 1')


season,rank,name,short_name,matchesplayed,matcheswon,matcheslost,noresult,matchpoints,nrr,for,against
0  2022,1,Gujarat Titans,GT,14,10,4,0,20,0.316,23...                                                   
1  2022,2,Rajasthan Royals,RR,14,9,5,0,18,0.298,2...                                                   
2  2022,3,Lucknow Super Giants,LSG,14,9,5,0,18,0....                                                   
3  2022,4,Royal Challengers Bangalore,RCB,14,8,6,...                                                   
4  2022,5,Delhi Capitals,DC,14,7,7,0,14,0.204,234...                                                   
5  2022,6,Punjab Kings,KXIP,14,7,7,0,14,0.126,234...                                                   
6  2022,7,Kolkata Knight Riders,KKR,14,6,8,0,12,0...                                                   
7  2022,8,Sunrisers Hyderabad,SRH,14,6,8,0,12,-0....                                                   
8  2022,9,Chennai Super Kings,CSK,14,4,10,0,8,-0....                                                   
9  2022,10,Mumbai Indians,MI,14,4,10,0,8,-0.506,2...

In [11]:
#Creating the DataFrame (All arrays must be of the same length)
df_dict = {'Year':[1990,1994,1998,2002],
          'Country':['Italy','USA','France','Japan'],
          'Winner':['Germany','Brazil','France','Brazil'],
          'Goals scored':[115,141,171,161]}
pd.DataFrame(df_dict)

Year Country   Winner  Goals scored
0  1990   Italy  Germany           115
1  1994     USA   Brazil           141
2  1998  France   France           171
3  2002   Japan   Brazil           161

In [13]:
#Creating the DataFrame using pd.series(no need of All arrays to be have same length)
df_pdseries = {'Year':pd.Series([1990,1994,1998,2002]),
               'Winner':pd.Series(['Germany','Brazil','France']),
               'Goals scored':pd.Series([115,141,171,161])}
pd.DataFrame(df_pdseries)

Year   Winner  Goals scored
0  1990  Germany           115
1  1994   Brazil           141
2  1998   France           171
3  2002      NaN           161

In [16]:
df = pd.read_csv(r'D:\Class\PYTHON\Python\2. Python class\18. Addition and Deletion of the elements\imdb_rating.csv')
df

star_rating                                          title      genre  \
0          9.3                       The Shawshank Redemption      Crime   
1          9.2                                  The Godfather      Crime   
2          9.1                         The Godfather: Part II      Crime   
3          9.0                                The Dark Knight     Action   
4          8.9                                   Pulp Fiction      Crime   
5          8.9                                   12 Angry Men      Drama   
6          8.9                 The Good, the Bad and the Ugly    Western   
7          8.9  The Lord of the Rings: The Return of the King  Adventure   
8          8.9                               Schindler's List  Biography   
9          8.9                                     Fight Club      Drama   

   duration  
0       142  
1       175  
2       200  
3       152  
4       154  
5        96  
6       161  
7       201  
8       195  
9       139

In [21]:
#To add the new column 
df['Review']='Good'
df.head()

star_rating                     title   genre  duration Review
0          9.3  The Shawshank Redemption   Crime       142   Good
1          9.2             The Godfather   Crime       175   Good
2          9.1    The Godfather: Part II   Crime       200   Good
3          9.0           The Dark Knight  Action       152   Good
4          8.9              Pulp Fiction   Crime       154   Good

In [33]:
#By indexing changing th value
df['Review'][1],df['Review'][2],df['Review'][3],df['Review'][9]='Bad','Bad','Bad','Bad'

C:\Users\admin\AppData\Local\Temp\ipykernel_10732\794058671.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Review'][1],df['Review'][2],df['Review'][3],df['Review'][9]='Bad','Bad','Bad','Bad'


In [32]:
#By slicing changing th value
df['Review'][1:6]='Bad'
df

C:\Users\admin\AppData\Local\Temp\ipykernel_10732\2220314254.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Review'][1:6]='Bad'


star_rating                                          title      genre  \
0          9.3                       The Shawshank Redemption      Crime   
1          9.2                                  The Godfather      Crime   
2          9.1                         The Godfather: Part II      Crime   
3          9.0                                The Dark Knight     Action   
4          8.9                                   Pulp Fiction      Crime   
5          8.9                                   12 Angry Men      Drama   
6          8.9                 The Good, the Bad and the Ugly    Western   
7          8.9  The Lord of the Rings: The Return of the King  Adventure   
8          8.9                               Schindler's List  Biography   
9          8.9                                     Fight Club      Drama   

   duration Review  
0       142   Good  
1       175    Bad  
2       200    Bad  
3       152    Bad  
4       154    Bad  
5        96    Bad  
6       161   Good  
7       201   Good  
8       195   Good  
9       139    Bad

In [37]:
#To del the column
del df['Review']

In [39]:
df.head()

star_rating                     title   genre  duration
0          9.3  The Shawshank Redemption   Crime       142
1          9.2             The Godfather   Crime       175
2          9.1    The Godfather: Part II   Crime       200
3          9.0           The Dark Knight  Action       152
4          8.9              Pulp Fiction   Crime       154

In [40]:
#To update the row to the table 
df.loc[5]=[9.0,'corona Paper','Thriller',190]

In [42]:
#To add the new row to the table 
df.loc[10]=[9.9,'Leo','Thriller',210]

In [43]:
df

star_rating                                          title      genre  \
0           9.3                       The Shawshank Redemption      Crime   
1           9.2                                  The Godfather      Crime   
2           9.1                         The Godfather: Part II      Crime   
3           9.0                                The Dark Knight     Action   
4           8.9                                   Pulp Fiction      Crime   
5           9.0                                   corona Paper   Thriller   
6           8.9                 The Good, the Bad and the Ugly    Western   
7           8.9  The Lord of the Rings: The Return of the King  Adventure   
8           8.9                               Schindler's List  Biography   
9           8.9                                     Fight Club      Drama   
10          9.9                                            Leo   Thriller   

    duration  
0        142  
1        175  
2        200  
3        152  
4        154  
5        190  
6        161  
7        201  
8        195  
9        139  
10       210

In [46]:
#To sort the value based on the column
df1=df.sort_values('star_rating',ascending=False)
df1.head()

star_rating                     title     genre  duration
10          9.9                       Leo  Thriller       210
0           9.3  The Shawshank Redemption     Crime       142
1           9.2             The Godfather     Crime       175
2           9.1    The Godfather: Part II     Crime       200
3           9.0           The Dark Knight    Action       152

In [47]:
#To sort the value based on the index
df1=df.sort_index()
df1.head()

star_rating                     title   genre  duration
0          9.3  The Shawshank Redemption   Crime       142
1          9.2             The Godfather   Crime       175
2          9.1    The Godfather: Part II   Crime       200
3          9.0           The Dark Knight  Action       152
4          8.9              Pulp Fiction   Crime       154

In [49]:
#To drop the specific rows from the table
df2=df.drop(df.index[[1,2]])
df2

star_rating                                          title      genre  \
0           9.3                       The Shawshank Redemption      Crime   
3           9.0                                The Dark Knight     Action   
4           8.9                                   Pulp Fiction      Crime   
5           9.0                                   corona Paper   Thriller   
6           8.9                 The Good, the Bad and the Ugly    Western   
7           8.9  The Lord of the Rings: The Return of the King  Adventure   
8           8.9                               Schindler's List  Biography   
9           8.9                                     Fight Club      Drama   
10          9.9                                            Leo   Thriller   

    duration  
0        142  
3        152  
4        154  
5        190  
6        161  
7        201  
8        195  
9        139  
10       210

In [51]:
#if u need to change the index as per the user
df.index=['movie_1','movie_2','movie_3','movie_4','movie_5','movie_6',
          'movie_7','movie_8','movie_9','movie_10','movie_11']

In [58]:
df.head()

star_rating                     title   genre  duration
movie_1          9.3  The Shawshank Redemption   Crime       142
movie_2          9.2             The Godfather   Crime       175
movie_3          9.1    The Godfather: Part II   Crime       200
movie_4          9.0           The Dark Knight  Action       152
movie_5          8.9              Pulp Fiction   Crime       154

In [60]:
#If u need to reset the index column
df1=df.reset_index()
df1.tail()

index  star_rating                                          title  \
6    movie_7          8.9                 The Good, the Bad and the Ugly   
7    movie_8          8.9  The Lord of the Rings: The Return of the King   
8    movie_9          8.9                               Schindler's List   
9   movie_10          8.9                                     Fight Club   
10  movie_11          9.9                                            Leo   

        genre  duration  
6     Western       161  
7   Adventure       201  
8   Biography       195  
9       Drama       139  
10   Thriller       210

In [65]:
#For drop the column from the table
df4=df1.drop(columns=['index'])
df4.tail()

star_rating                                          title      genre  \
6           8.9                 The Good, the Bad and the Ugly    Western   
7           8.9  The Lord of the Rings: The Return of the King  Adventure   
8           8.9                               Schindler's List  Biography   
9           8.9                                     Fight Club      Drama   
10          9.9                                            Leo   Thriller   

    duration  
6        161  
7        201  
8        195  
9        139  
10       210

In [ ]:
# Selection and Indexing

In [66]:
# to access the only one column from the table
df['title'].head(6)

movie_1    The Shawshank Redemption
movie_2               The Godfather
movie_3      The Godfather: Part II
movie_4             The Dark Knight
movie_5                Pulp Fiction
movie_6                corona Paper
Name: title, dtype: object

In [68]:
df[['title','genre']].tail(5)

title      genre
movie_7                  The Good, the Bad and the Ugly    Western
movie_8   The Lord of the Rings: The Return of the King  Adventure
movie_9                                Schindler's List  Biography
movie_10                                     Fight Club      Drama
movie_11                                            Leo   Thriller

In [73]:
#To check the specific row in the table
df5=df.at['movie_8','title']
df5

'The Lord of the Rings: The Return of the King'

In [74]:
#To update the specific row in the table
df.at['movie_8','title']='KGF 2'

In [76]:
df.at['movie_8','title']

'KGF 2'

In [78]:
#To know the details of certain rows from th table
df.loc['movie_11']

star_rating         9.9
title               Leo
genre          Thriller
duration            210
Name: movie_11, dtype: object

In [80]:
#To slice the rows
df8=df.loc['movie_5':'movie_9']
df8

star_rating                           title      genre  duration
movie_5          8.9                    Pulp Fiction      Crime       154
movie_6          9.0                    corona Paper   Thriller       190
movie_7          8.9  The Good, the Bad and the Ugly    Western       161
movie_8          8.9                           KGF 2  Adventure       201
movie_9          8.9                Schindler's List  Biography       195

In [82]:
#To slice the column from the table
df9=df8.loc['movie_5':,'star_rating':'genre']
df9

star_rating                           title      genre
movie_5          8.9                    Pulp Fiction      Crime
movie_6          9.0                    corona Paper   Thriller
movie_7          8.9  The Good, the Bad and the Ugly    Western
movie_8          8.9                           KGF 2  Adventure
movie_9          8.9                Schindler's List  Biography

In [89]:
#Appling the condition filter onj the table values
df10 = df.loc[df['star_rating']>=9.0]
df10.sort_values('star_rating')

star_rating                     title     genre  duration
movie_4           9.0           The Dark Knight    Action       152
movie_6           9.0              corona Paper  Thriller       190
movie_3           9.1    The Godfather: Part II     Crime       200
movie_2           9.2             The Godfather     Crime       175
movie_1           9.3  The Shawshank Redemption     Crime       142
movie_11          9.9                       Leo  Thriller       210

In [90]:
#For implict index as 0,,1,2,3,4,5,6,.... use iloc[]
df11 = df.iloc[4:8]
df11

star_rating                           title      genre  duration
movie_5          8.9                    Pulp Fiction      Crime       154
movie_6          9.0                    corona Paper   Thriller       190
movie_7          8.9  The Good, the Bad and the Ugly    Western       161
movie_8          8.9                           KGF 2  Adventure       201

In [91]:
#if we need all the columns but only three rows specific
df12 = df.iloc[[2,5,7],:]
df12

star_rating                   title      genre  duration
movie_3          9.1  The Godfather: Part II      Crime       200
movie_6          9.0            corona Paper   Thriller       190
movie_8          8.9                   KGF 2  Adventure       201

In [94]:
#for filtering the specific value from the columns
df13=df[df['genre']=='Crime']
df13

star_rating                     title  genre  duration
movie_1          9.3  The Shawshank Redemption  Crime       142
movie_2          9.2             The Godfather  Crime       175
movie_3          9.1    The Godfather: Part II  Crime       200
movie_5          8.9              Pulp Fiction  Crime       154

In [98]:
#for filtering more than one specific value from the columns use &
df14=df[(df['genre']=='Crime') & (df['star_rating']>9.0)]
df14

star_rating                     title  genre  duration
movie_1          9.3  The Shawshank Redemption  Crime       142
movie_2          9.2             The Godfather  Crime       175
movie_3          9.1    The Godfather: Part II  Crime       200

In [99]:
#filtering either value from the columns |
df15=df[(df['genre']=='Crime') | (df['star_rating']>9.0)]
df15

star_rating                     title     genre  duration
movie_1           9.3  The Shawshank Redemption     Crime       142
movie_2           9.2             The Godfather     Crime       175
movie_3           9.1    The Godfather: Part II     Crime       200
movie_5           8.9              Pulp Fiction     Crime       154
movie_11          9.9                       Leo  Thriller       210

In [102]:
#for not equal to != or ~
df16=df[(df['genre']!='Crime')]
df16

star_rating                           title      genre  duration
movie_4           9.0                 The Dark Knight     Action       152
movie_6           9.0                    corona Paper   Thriller       190
movie_7           8.9  The Good, the Bad and the Ugly    Western       161
movie_8           8.9                           KGF 2  Adventure       201
movie_9           8.9                Schindler's List  Biography       195
movie_10          8.9                      Fight Club      Drama       139
movie_11          9.9                             Leo   Thriller       210

In [ ]:
Reshaping a Dataframe

In [103]:
sf = pd.read_csv(r'D:\Class\PYTHON\Python\2. Python class\18. Addition and Deletion of the elements/avocado.csv')
sf

Region          Type  Small Bags  Large Bags  Total Bags  \
0       Atlanta       organic    89424.11      207.08    89631.19   
1       Atlanta  conventional   102717.50      153.00   102870.50   
2        Boston       organic   120465.39       18.83   120484.22   
3        Boston  conventional   136877.43       60.60   136938.03   
4    California       organic    66273.89       46.58    66320.47   
5    California  conventional   103033.73      186.20   106984.89   
6       NewYork       organic   119694.95       92.29   124214.59   
7       NewYork  conventional   193813.92      196.57   197281.89   
8  SanFrancisco       organic   231913.11     1286.43   236417.93   
9  SanFrancisco  conventional   162913.33      609.20   166836.16   

   Total Volume  AveragePrice        Date  
0     190257.38          1.70  2018-03-25  
1     202790.74          1.75  2018-03-18  
2     236822.98          1.58  2018-03-11  
3     239135.67          1.57  2018-03-04  
4     179041.72          1.82  2018-02-25  
5    1203274.11          1.01  2018-03-25  
6     777300.99          1.38  2018-03-18  
7     904333.98          1.29  2018-03-11  
8    1051308.50          1.16  2018-03-04  
9     984000.13          1.17  2018-02-25

In [104]:
#Converting the table to pivot style
sf1=sf.pivot(index='Region',columns='Type')
sf1

Small Bags              Large Bags            Total Bags  \
Type         conventional    organic conventional  organic conventional   
Region                                                                    
Atlanta         102717.50   89424.11       153.00   207.08    102870.50   
Boston          136877.43  120465.39        60.60    18.83    136938.03   
California      103033.73   66273.89       186.20    46.58    106984.89   
NewYork         193813.92  119694.95       196.57    92.29    197281.89   
SanFrancisco    162913.33  231913.11       609.20  1286.43    166836.16   

                        Total Volume             AveragePrice          \
Type            organic conventional     organic conventional organic   
Region                                                                  
Atlanta        89631.19    202790.74   190257.38         1.75    1.70   
Boston        120484.22    239135.67   236822.98         1.57    1.58   
California     66320.47   1203274.11   179041.72         1.01    1.82   
NewYork       124214.59    904333.98   777300.99         1.29    1.38   
SanFrancisco  236417.93    984000.13  1051308.50         1.17    1.16   

                     Date              
Type         conventional     organic  
Region                                 
Atlanta        2018-03-18  2018-03-25  
Boston         2018-03-04  2018-03-11  
California     2018-03-25  2018-02-25  
NewYork        2018-03-11  2018-03-18  
SanFrancisco   2018-02-25  2018-03-04

In [107]:
sf1=sf.pivot(index='Region',columns='Type',values=['AveragePrice','Date'])
sf1

AveragePrice                 Date            
Type         conventional organic conventional     organic
Region                                                    
Atlanta              1.75     1.7   2018-03-18  2018-03-25
Boston               1.57    1.58   2018-03-04  2018-03-11
California           1.01    1.82   2018-03-25  2018-02-25
NewYork              1.29    1.38   2018-03-11  2018-03-18
SanFrancisco         1.17    1.16   2018-02-25  2018-03-04

In [109]:
#For multiindex purpose
mf=pd.read_csv(r'D:\Class\PYTHON\Python\2. Python class\18. Addition and Deletion of the elements/avocado.csv',
               index_col=['Region','Type'])
mf

Small Bags  Large Bags  Total Bags  Total Volume  \
Region       Type                                                             
Atlanta      organic         89424.11      207.08    89631.19     190257.38   
             conventional   102717.50      153.00   102870.50     202790.74   
Boston       organic        120465.39       18.83   120484.22     236822.98   
             conventional   136877.43       60.60   136938.03     239135.67   
California   organic         66273.89       46.58    66320.47     179041.72   
             conventional   103033.73      186.20   106984.89    1203274.11   
NewYork      organic        119694.95       92.29   124214.59     777300.99   
             conventional   193813.92      196.57   197281.89     904333.98   
SanFrancisco organic        231913.11     1286.43   236417.93    1051308.50   
             conventional   162913.33      609.20   166836.16     984000.13   

                           AveragePrice        Date  
Region       Type                                    
Atlanta      organic               1.70  2018-03-25  
             conventional          1.75  2018-03-18  
Boston       organic               1.58  2018-03-11  
             conventional          1.57  2018-03-04  
California   organic               1.82  2018-02-25  
             conventional          1.01  2018-03-25  
NewYork      organic               1.38  2018-03-18  
             conventional          1.29  2018-03-11  
SanFrancisco organic               1.16  2018-03-04  
             conventional          1.17  2018-02-25